CREATE TABLE IF NOT EXISTS address
( id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY

, street_address VARCHAR(128)
, city VARCHAR(64)
, zip INT(5)

, state VARCHAR(20)

, FOREIGN KEY (state) REFERENCES state (name)
);
