CREATE TABLE verbs
(
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	base VARCHAR(64) NOT NULL,
	past VARCHAR(64) DEFAULT NULL,
	present VARCHAR(64) DEFAULT NULL,
	is_transitive BOOLEAN DEFAULT FALSE
);
