CREATE TABLE nouns
(
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	base VARCHAR(64) NOT NULL,
	plural VARCHAR(64) DEFAULT NULL,
	is_proper BOOLEAN DEFAULT FALSE,
	is_abstract BOOLEAN DEFAULT FALSE
);
