INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Tomb',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Dagon',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('A Reminiscence of Dr. Samuel Johnson',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Polaris',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Beyond the Wall of Sleep',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Memory',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Old Bugs',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Transition of Juan Romero',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The White Ship',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Doom that Came to Sarnath',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Statement of Randolph Carter',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Street',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Terrible Old Man',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Cats of Ulthar',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Tree',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Celephaïs',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('From Beyond',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Temple',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Nyarlathotep',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Picture in the House',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Facts Concerning the Late Arthur Jermyn and His Family',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Nameless City',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Quest of Iranon',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Moon-Bog',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Ex Oblivione',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Other Gods',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Outsider',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Music of Erich Zann',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Sweet Ermengarde',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Hypnos',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('What the Moon Brings',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Azathoth',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Herbert West–Reanimator',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Hound',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Lurking Fear',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Rats in the Walls',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Unnamable',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Festival',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Shunned House',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Horror at Red Hook',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('He',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('In the Vault',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Cool Air',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Call of Cthulhu',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Pickman\'s Model',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Strange High House in the Mist',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Silver Key',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Dream-Quest of Unknown Kadath',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Case of Charles Dexter Ward',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Colour Out of Space',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Descendant',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Very Old Folk',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('History of the Necronomicon',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Dunwich Horror',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('Ibid',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Whisperer in Darkness',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('At the Mountains of Madness',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Shadow Over Innsmouth',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Dreams in the Witch House',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Thing on the Doorstep',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Book',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Evil Clergyman',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Shadow Out of Time',1,1,1);
INSERT INTO book (title, publisher_id, author_id, genre_id) VALUES ('The Haunter of the Dark',1,1,1); 